
; ++++++++++ BASE ENV ++++++++++
[_env_base]
upload_speed = 921600
monitor_speed = 115200
build_src_filter = -<*>
lib_deps =
    jescore@^2.3.0
lib_ignore = lib/*
; ---------- BASE ENV ---------- 

; ++++++++++ ESP32 BOARDS ++++++++++
[_env:esp32]
extends = _env_base
platform = espressif32
platform_packages = tool-esptoolpy@~1.40501.0

[_env:esp32-arduino]
extends = _env:esp32
framework = arduino
test_filter = test_arduino

[_env:esp32-az-delivery-devkit-v4-arduino]
extends = _env:esp32-arduino
board = az-delivery-devkit-v4
upload_protocol = esptool
build_flags =
    -DLED_BUILTIN=5

[_env:esp32-c3-arduino]
extends = _env:esp32-arduino
board = esp32-c3-devkitm-1

[_env:esp32-wrover-kit-arduino]
extends = _env:esp32-arduino
board = esp-wrover-kit
build_flags = 
    -DLED_BUILTIN=5

[_env:esp32-nodemcu-arduino]
extends = _env:esp32-arduino
board = nodemcu-32s
; ---------- ESP32 BOARDS ---------- 

; ++++++++++ STM32 BOARDS ++++++++++
[_env:stm32]
extends = _env_base
platform = ststm32
test_transport = custom
test_filter = test_stm32cube
lib_archive = no

[_env:stm32-cube]
extends = _env:stm32
framework = stm32cube
build_flags = 
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16

[_env:nucleol432kc-cube]
extends = _env:stm32-cube
board = nucleo_l432kc
upload_protocol = stlink 

[_env:nucleol476rg-cube]
extends = _env:stm32-cube
board = nucleo_l476rg
upload_protocol = stlink 
; ---------- STM32 BOARDS ---------- 

; ++++++++++ EXAMPLES ++++++++++
; +++ Hello World +++
[env:hello_world_nucleol432kc-cube]
extends = _env:nucleol432kc-cube
build_src_filter = +<hello_world_nucleol432kc.c>

[env:hello_world_nucleol476rg-cube]
extends = _env:nucleol476rg-cube
build_src_filter = +<hello_world_nucleol476rg.c>

[env:hello_world_esp32-c3-arduino]
extends = _env:esp32-c3-arduino
build_src_filter = +<hello_world_arduino.cpp>

[env:hello_world_esp32-az-delivery-devkit-v4-arduino]
extends = _env:esp32-az-delivery-devkit-v4-arduino
build_src_filter = +<hello_world_arduino.cpp>

[env:hello_world_esp32-wrover-kit-arduino]
extends = _env:esp32-wrover-kit-arduino
build_src_filter = +<hello_world_arduino.cpp>

[env:hello_world_esp32-nodemcu-arduino]
extends = _env:esp32-nodemcu-arduino
build_src_filter = +<hello_world_arduino.cpp>
; --- Hello World ---

; +++ Multi UART Streamer +++
[env:multi_uart_streamer_esp32-c3-arduino]
extends = _env:esp32-c3-arduino
build_src_filter = +<multi_uart_streamer_arduino.cpp>
lib_deps = jesdev-io/jescore@^2.2.3

[env:multi_uart_streamer_esp32-az-delivery-devkit-v4-arduino]
extends = _env:esp32-az-delivery-devkit-v4-arduino
build_src_filter = +<multi_uart_streamer_arduino.cpp>
lib_deps = jesdev-io/jescore@^2.2.3

[env:multi_uart_streamer_esp32-wrover-kit-arduino]
extends = _env:esp32-wrover-kit-arduino
build_src_filter = +<multi_uart_streamer_arduino.cpp>
lib_deps = jesdev-io/jescore@^2.2.3

[env:multi_uart_streamer_esp32-nodemcu-arduino]
extends = _env:esp32-nodemcu-arduino
build_src_filter = +<multi_uart_streamer_arduino.cpp>
lib_deps = jesdev-io/jescore@^2.2.3
; --- Multi UART Streamer ---

; +++ Sync-Async +++
[env:sync_async_esp32-c3-arduino]
extends = _env:esp32-c3-arduino
build_src_filter = +<sync_async_arduino.cpp>

[env:sync_async_esp32-az-delivery-devkit-v4-arduino]
extends = _env:esp32-az-delivery-devkit-v4-arduino
build_src_filter = +<sync_async_arduino.cpp>

[env:sync_async_esp32-wrover-kit-arduino]
extends = _env:esp32-wrover-kit-arduino
build_src_filter = +<sync_async_arduino.cpp>

[env:sync_async_esp32-nodemcu-arduino]
extends = _env:esp32-nodemcu-arduino
build_src_filter = +<sync_async_arduino.cpp>
; --- Sync-Async ---

; +++ FSM CLI +++
[env:fsm_cli_esp32-c3-arduino]
extends = _env:esp32-c3-arduino
build_src_filter = +<fsm_cli_arduino.cpp>

[env:fsm_cli_esp32-az-delivery-devkit-v4-arduino]
extends = _env:esp32-az-delivery-devkit-v4-arduino
build_src_filter = +<fsm_cli_arduino.cpp>

[env:fsm_cli_esp32-wrover-kit-arduino]
extends = _env:esp32-wrover-kit-arduino
build_src_filter = +<fsm_cli_arduino.cpp>
; --- FSM CLI ---

; +++ Stereo SPL Meter +++
[env:stereo_spl_meter_nucleol432kc-cube]
extends = _env:nucleol432kc-cube
lib_ignore = 
        ${_env_base.lib_ignore}
        !lib/port_stereo_spl_meter_stm32
        !lib/utils
build_src_filter = +<stereo_spl_meter_nucleol432kc.c>
; --- Stereo SPL Meter ---

; +++ Stereo Matrix Filter +++
[env:stereo_matrix_filter_nucleol476rg-cube]
extends = _env:nucleol476rg-cube
lib_deps = 
        ${_env:nucleol476rg-cube.lib_deps}
        https://github.com/maxgerhardt/pio-CMSIS-DSP
lib_ignore = 
        ${_env:nucleol476rg-cube.lib_ignore}
        !lib/port_stereo_matrix_filter
        !lib/utils
build_flags = 
        ${_env:nucleol476rg-cube.build_flags}
        -O2
build_src_filter = +<stereo_matrix_filter_nucleol476rg.c>
; --- Stereo Matrix Filter ---

; ---------- EXAMPLES ---------- 