
; ++++++++++ BASE ENV ++++++++++
[_env_base]
upload_speed = 921600
monitor_speed = 115200
build_src_filter = -<*>
lib_deps =
    jescore
; ---------- BASE ENV ---------- 

; ++++++++++ ESP32 BOARDS ++++++++++
[_env:esp32]
extends = _env_base
platform = espressif32

[_env:esp32-arduino]
extends = _env:esp32
framework = arduino
test_filter = test_arduino

[_env:esp32-az-delivery-devkit-v4-arduino]
extends = _env:esp32-arduino
board = az-delivery-devkit-v4
upload_protocol = esptool
build_flags =
    -DLED_BUILTIN=5

[_env:esp32-c3-arduino]
extends = _env:esp32-arduino
board = esp32-c3-devkitm-1

[_env:esp32-wrover-kit-arduino]
extends = _env:esp32-arduino
board = esp-wrover-kit
build_flags = 
    -DLED_BUILTIN=5

[_env:esp32-nodemcu-arduino]
extends = _env:esp32-arduino
board = nodemcu-32s
; ---------- ESP32 BOARDS ---------- 

; ++++++++++ STM32 BOARDS ++++++++++
[_env:stm32]
extends = _env_base
platform = ststm32
test_transport = custom
test_filter = test_stm32cube
lib_archive = no

[_env:stm32-cube]
extends = _env:stm32
framework = stm32cube
build_flags = 
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16

[_env:nucleol432kc-cube]
extends = _env:stm32-cube
board = nucleo_l432kc
upload_protocol = stlink 
; ---------- STM32 BOARDS ---------- 

; ++++++++++ EXAMPLES ++++++++++
; +++ Hello World +++
[env:hello_world_nucleol432kc-cube]
extends = _env:nucleol432kc-cube
build_src_filter = +<hello_world_nucleol432kc.c>

[env:hello_world_esp32-c3-arduino]
extends = _env:esp32-c3-arduino
build_src_filter = +<hello_world_arduino.cpp>

[env:hello_world_esp32-az-delivery-devkit-v4-arduino]
extends = _env:esp32-az-delivery-devkit-v4-arduino
build_src_filter = +<hello_world_arduino.cpp>

[env:hello_world_esp32-wrover-kit-arduino]
extends = _env:esp32-wrover-kit-arduino
build_src_filter = +<hello_world_arduino.cpp>

[env:hello_world_esp32-nodemcu-arduino]
extends = _env:esp32-nodemcu-arduino
build_src_filter = +<hello_world_arduino.cpp>
; --- Hello World ---

; +++ Sync-Async +++
[env:sync_async_esp32-c3-arduino]
extends = _env:esp32-c3-arduino
build_src_filter = +<sync_async_arduino.cpp>

[env:sync_async_esp32-az-delivery-devkit-v4-arduino]
extends = _env:esp32-az-delivery-devkit-v4-arduino
build_src_filter = +<sync_async_arduino.cpp>

[env:sync_async_esp32-wrover-kit-arduino]
extends = _env:esp32-wrover-kit-arduino
build_src_filter = +<sync_async_arduino.cpp>

[env:sync_async_esp32-nodemcu-arduino]
extends = _env:esp32-nodemcu-arduino
build_src_filter = +<sync_async_arduino.cpp>
; --- Sync-Async ---

; +++ FSM CLI +++
[env:fsm_cli_esp32-c3-arduino]
extends = _env:esp32-c3-arduino
build_src_filter = +<fsm_cli_arduino.cpp>

[env:fsm_cli_esp32-az-delivery-devkit-v4-arduino]
extends = _env:esp32-az-delivery-devkit-v4-arduino
build_src_filter = +<fsm_cli_arduino.cpp>

[env:fsm_cli_esp32-wrover-kit-arduino]
extends = _env:esp32-wrover-kit-arduino
build_src_filter = +<fsm_cli_arduino.cpp>
; --- FSM CLI ---

; +++ Stereo SPL Meter +++
[env:stereo_spl_meter_nucleol432kc-cube]
extends = _env:nucleol432kc-cube
build_src_filter = +<stereo_spl_meter_stm32.c>
; --- Stereo SPL Meter ---

; ---------- EXAMPLES ---------- 