; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[_env_base]
upload_speed = 921600
monitor_speed = 115200
build_src_filter = -<*>
lib_deps =
    jescore

[_env:esp32]
extends = _env_base
platform = espressif32

[_env:esp32-arduino]
extends = _env:esp32
framework = arduino
test_filter = test_arduino

[_env:stm32]
extends = _env_base
platform = ststm32
test_transport = custom
test_filter = test_stm32cube

[_env:stm32-cube]
extends = _env:stm32
framework = stm32cube
build_flags = 
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16

[_env:nucleol432kc-release-cube]
extends = _env:stm32-cube
board = nucleo_l432kc
upload_protocol = stlink 
lib_archive = no
monitor_speed = 115200
build_type = debug
debug_build_flags = -O0 -g -ggdb

[env:hello_world_nucleol432kc]
extends = _env:nucleol432kc-release-cube
build_src_filter = +<hello_world_nucleol432kc.c>

[env:i2s_line_array_nucleol432kc]
extends = _env:nucleol432kc-release-cube
build_flags =   ${_env:stm32-cube.build_flags}
                -I$PROJECT_PACKAGES_DIR/framework-stm32cubel4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc
                -I$PROJECT_PACKAGES_DIR/framework-stm32cubel4/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc
                -Ilib/usb_hooks_nucleol432kc
                -Ilib/port_i2s_line_array_nucleol432kc
build_src_filter =  ${_env:stm32.build_src_filter} 
                    -I$PROJECT_PACKAGES_DIR/framework-stm32cubel4/Middlewares/ST/STM32_USB_Device_Library/Core/Src/*.c
                    -I$PROJECT_PACKAGES_DIR/framework-stm32cubel4/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Src/*.c
                    +<lib/usb_hooks_nucleol432kc/*.c>
                    +<i2s_line_array_nucleol432kc.c>