#ifndef TUSB_CONFIG_H_
#define TUSB_CONFIG_H_

#ifdef __cplusplus
extern "C" {
#endif

#define BOARD_TUD_RHPORT       0
#define BOARD_TUD_MAX_SPEED    OPT_MODE_FULL_SPEED

#ifndef CFG_TUSB_MCU
#define CFG_TUSB_MCU           OPT_MCU_STM32H7
#endif
#define CFG_TUSB_OS            OPT_OS_FREERTOS
#define CFG_TUSB_DEBUG         0
#define CFG_TUD_ENABLED        1
#define CFG_TUD_MAX_SPEED      OPT_MODE_FULL_SPEED
#define CFG_TUD_ENDPOINT0_SIZE 64

#define CFG_TUSB_MEM_SECTION
#define CFG_TUSB_MEM_ALIGN     __attribute__((aligned(4)))

#define CFG_TUD_CDC            0
#define CFG_TUD_MSC            0
#define CFG_TUD_HID            0
#define CFG_TUD_MIDI           0
#define CFG_TUD_VENDOR         0
#define CFG_TUD_AUDIO          1

#define CFG_TUD_AUDIO_ENABLE_INTERRUPT_EP 0
#define CFG_TUD_AUDIO_FUNC_1_N_FORMATS 1
#define CFG_TUD_AUDIO_FUNC_1_MAX_SAMPLE_RATE 48000
#define CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_TX 1 /* microphone to host */
#define CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX 2 /* speaker from host */

#define CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX 2
#define CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX 16
#define CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX 2
#define CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX 16

#define CFG_TUD_AUDIO_ENABLE_EP_IN  1
#define CFG_TUD_AUDIO_ENABLE_EP_OUT 1
#define CFG_TUD_AUDIO_ENABLE_FEEDBACK_EP 0
#define CFG_TUD_AUDIO_EP_IN_FLOW_CONTROL 0

#define CFG_TUD_AUDIO10_FUNC_1_FORMAT_1_EP_SZ_IN  TUD_AUDIO_EP_SIZE(false, CFG_TUD_AUDIO_FUNC_1_MAX_SAMPLE_RATE, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_TX)
#define CFG_TUD_AUDIO10_FUNC_1_FORMAT_1_EP_SZ_OUT TUD_AUDIO_EP_SIZE(false, CFG_TUD_AUDIO_FUNC_1_MAX_SAMPLE_RATE, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX)
#define CFG_TUD_AUDIO20_FUNC_1_FORMAT_1_EP_SZ_IN  CFG_TUD_AUDIO10_FUNC_1_FORMAT_1_EP_SZ_IN
#define CFG_TUD_AUDIO20_FUNC_1_FORMAT_1_EP_SZ_OUT CFG_TUD_AUDIO10_FUNC_1_FORMAT_1_EP_SZ_OUT
#define CFG_TUD_AUDIO20_FUNC_1_FORMAT_2_EP_SZ_IN  CFG_TUD_AUDIO10_FUNC_1_FORMAT_1_EP_SZ_IN
#define CFG_TUD_AUDIO20_FUNC_1_FORMAT_2_EP_SZ_OUT CFG_TUD_AUDIO10_FUNC_1_FORMAT_1_EP_SZ_OUT

#define CFG_TUD_AUDIO_FUNC_1_EP_IN_SZ_MAX  CFG_TUD_AUDIO10_FUNC_1_FORMAT_1_EP_SZ_IN
#define CFG_TUD_AUDIO_FUNC_1_EP_OUT_SZ_MAX CFG_TUD_AUDIO10_FUNC_1_FORMAT_1_EP_SZ_OUT
#define CFG_TUD_AUDIO_FUNC_1_EP_IN_SW_BUF_SZ  (8 * CFG_TUD_AUDIO_FUNC_1_EP_IN_SZ_MAX)
#define CFG_TUD_AUDIO_FUNC_1_EP_OUT_SW_BUF_SZ (8 * CFG_TUD_AUDIO_FUNC_1_EP_OUT_SZ_MAX)

#ifdef __cplusplus
}
#endif

#endif
